# Generated by Django 5.0.9 on 2024-12-01 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Type_of_applicant",
                    models.CharField(
                        choices=[
                            ("SH", "Senior HighSchool Graduate"),
                            ("AL", "Alternative Learning System"),
                            ("CE", "Currently enrolled Grade12 student"),
                            ("BD", "Bachelor degree graduate"),
                            ("TC", "Teacher certificate program applicant"),
                            ("TF", "Transferee"),
                            ("DC", "Diploma certificate associate vocational graduate"),
                        ],
                        default="SH",
                        max_length=2,
                    ),
                ),
                (
                    "senior_high_school_track",
                    models.CharField(
                        choices=[
                            ("AC", "Academic"),
                            ("AD", "Arts and Design"),
                            ("SP", "Sports"),
                            ("TL", "Technical Vocational Livelihood"),
                        ],
                        default="TL",
                        max_length=2,
                    ),
                ),
                (
                    "Senior_high_school_strand",
                    models.CharField(
                        choices=[
                            ("ST", "Science, Technology, Engineering and Mathematics"),
                            ("it", "Information Technology"),
                        ],
                        default="it",
                        max_length=2,
                    ),
                ),
                (
                    "Preferred_program",
                    models.CharField(
                        choices=[
                            ("BC", "BS Computer Science"),
                            ("BT", "BS Information Technology"),
                        ],
                        default="BC",
                        max_length=2,
                    ),
                ),
                ("full_name", models.CharField(max_length=250)),
                ("Given_name", models.CharField(max_length=250)),
                ("Middle_name", models.CharField(blank=True, max_length=250)),
                ("last_name", models.CharField(blank=True, max_length=250)),
                ("Suffix", models.CharField(blank=True, max_length=250)),
                ("Date_of_birth", models.DateField()),
                ("Contact_number", models.CharField(max_length=250)),
                ("photo", models.ImageField(blank=True, upload_to="user/%Y/%m/%d")),
                ("Address_line_1", models.CharField(max_length=250)),
                ("Address_line_2", models.CharField(max_length=250)),
                ("City", models.CharField(max_length=250)),
                ("State_Province_Region", models.CharField(max_length=250)),
                ("Postal_code", models.CharField(max_length=250)),
                ("number_of_siblings", models.IntegerField(default=0)),
                (
                    "income_bracket",
                    models.CharField(
                        choices=[
                            ("0", "0-25k"),
                            ("1", "25k-50k"),
                            ("2", "50k-100k"),
                            ("3", "100k+"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
                ("Fathers_name", models.CharField(blank=True, max_length=250)),
                ("Father_Contact_number", models.CharField(blank=True, max_length=250)),
                ("Father_Occupation", models.CharField(blank=True, max_length=250)),
                ("Father_has_attended_college", models.BooleanField()),
                ("Mother_name", models.CharField(blank=True, max_length=250)),
                ("Mother_Contact_number", models.CharField(blank=True, max_length=250)),
                ("Mother_Occupation", models.CharField(blank=True, max_length=250)),
                ("Mother_has_attended_college", models.BooleanField()),
                ("Guardian_name", models.CharField(max_length=250)),
                ("Guardian_Contact_number", models.CharField(max_length=250)),
                ("Guardian_Occupation", models.CharField(max_length=250)),
                ("Elementary_School_name", models.CharField(max_length=250)),
                ("Elementary_School_Address", models.CharField(max_length=250)),
                ("Elementary_Type_of_school", models.CharField(max_length=250)),
                ("Elementary_Year_of_graduated", models.CharField(max_length=250)),
                ("Senior_High_School_Name", models.CharField(max_length=250)),
                ("Senior_High_School_Address", models.CharField(max_length=250)),
                ("Senior_High_School_Type_of_School", models.CharField(max_length=250)),
                ("Senior_High_School_Graduated", models.CharField(max_length=250)),
                ("College_School_name", models.CharField(max_length=250)),
                ("College_Enrolled_Program", models.CharField(max_length=250)),
                ("College_School_Address", models.CharField(max_length=250)),
                ("College_Type_of_School", models.CharField(max_length=250)),
                ("College_Year_Graduated", models.CharField(max_length=250)),
                (
                    "Report_Card",
                    models.ImageField(upload_to="Admission/Report_Card/%Y/%m/%d"),
                ),
                ("Form_137", models.ImageField(upload_to="Admission/Form137/%Y/%m/%d")),
                (
                    "Passport",
                    models.ImageField(
                        blank=True, upload_to="Admission/passport/%Y/%m/%d"
                    ),
                ),
                (
                    "Additional_Documents",
                    models.ImageField(
                        blank=True, upload_to="Admission/passport/%Y/%m/%d"
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("publish_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-create_at"],
            },
        ),
    ]
