# Generated by Django 5.0.9 on 2024-11-20 06:32

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Type_of_applicant",
                    models.CharField(
                        choices=[
                            ("SH", "Senior HighSchool Graduate"),
                            ("AL", "Alternative Learning System"),
                            ("FU", "Foreign undergraduate student applicant"),
                            ("CE", "Currently enrolled Grade12 student"),
                            ("BD", "Bachelor degree graduate"),
                            ("TC", "Teacher certificate program applicant"),
                            ("TF", "Transferee"),
                            ("DC", "Diploma certificate associate vocational graduate"),
                        ],
                        default="SH",
                        max_length=2,
                    ),
                ),
                (
                    "senior_high_school_track",
                    models.CharField(
                        choices=[
                            ("AC", "Academic"),
                            ("AD", "Arts and Design"),
                            ("SP", "Sports"),
                            ("TL", "Technical Vocational Livelihood"),
                        ],
                        default="AC",
                        max_length=2,
                    ),
                ),
                (
                    "Senior_high_school_strand",
                    models.CharField(
                        choices=[
                            ("AB", "Accountancy Business Management"),
                            ("ST", "Science, Technology, Engineering and Mathematics"),
                            ("HS", "Humanities and Social Science"),
                            ("GA", "General Academic"),
                        ],
                        default="AB",
                        max_length=2,
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
