# Generated by Django 5.0.9 on 2024-12-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0002_alter_admission_type_of_applicant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="Type_of_applicant",
            field=models.CharField(
                choices=[
                    ("SH", "Senior HighSchool Graduate"),
                    ("AL", "Alternative Learning System"),
                    ("CE", "Currently enrolled Grade12 student"),
                    ("BD", "Bachelor degree graduate"),
                    ("TC", "Teacher certificate program applicant"),
                    ("TF", "Transferee"),
                    ("DC", "Diploma certificate associate vocational graduate"),
                ],
                max_length=2,
            ),
        ),
    ]
