# Generated by Django 5.0.9 on 2024-11-21 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0003_rename_country_admission_nationality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="full_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
