# Generated by Django 5.0.9 on 2024-12-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0003_alter_admission_type_of_applicant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="Preferred_program",
            field=models.CharField(
                choices=[
                    ("BC", "BS Computer Science"),
                    ("BT", "BS Information Technology"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="admission",
            name="Senior_high_school_strand",
            field=models.CharField(
                choices=[
                    ("ST", "Science, Technology, Engineering and Mathematics"),
                    ("it", "Information Technology"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="admission",
            name="senior_high_school_track",
            field=models.CharField(
                choices=[
                    ("AC", "Academic"),
                    ("AD", "Arts and Design"),
                    ("SP", "Sports"),
                    ("TL", "Technical Vocational Livelihood"),
                ],
                max_length=2,
            ),
        ),
    ]
