# Generated by Django 5.0.9 on 2024-12-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0004_alter_admission_preferred_program_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="Waitlist",
            field=models.CharField(
                choices=[("PE", "PENDING"), ("DO", "DONE")], default="PE", max_length=2
            ),
        ),
    ]
