# Generated by Django 5.0.9 on 2024-11-23 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Enrollments",
            "0005_admission_address_line_1_admission_address_line_2_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="admission",
            old_name="Nationality",
            new_name="Country",
        ),
    ]
