# Generated by Django 5.0.9 on 2024-11-23 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0006_rename_nationality_admission_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="Number_of_siblings",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admission",
            name="income_bracket",
            field=models.CharField(
                choices=[
                    ("2", "0-25k"),
                    ("2", "25k-50k"),
                    ("2", "50k-100k"),
                    ("3", "100k+"),
                ],
                default=django.utils.timezone.now,
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
