# Generated by Django 5.0.9 on 2024-11-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0007_admission_number_of_siblings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="income_bracket",
            field=models.CharField(
                choices=[
                    ("0", "0-25k"),
                    ("1", "25k-50k"),
                    ("2", "50k-100k"),
                    ("3", "100k+"),
                ],
                default="0",
                max_length=1,
            ),
        ),
    ]
