# Generated by Django 5.0.9 on 2024-11-23 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0008_alter_admission_income_bracket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admission",
            name="Number_of_siblings",
        ),
        migrations.AddField(
            model_name="admission",
            name="number_of_siblings",
            field=models.IntegerField(
                default=0
            ),
            preserve_default=False,
        ),
    ]
