# Generated by Django 5.0.9 on 2024-11-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0009_remove_admission_number_of_siblings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="number_of_siblings",
            field=models.IntegerField(default=0),
        ),
    ]
