# Generated by Django 5.0.9 on 2024-11-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0010_alter_admission_number_of_siblings"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="photo",
            field=models.ImageField(blank=True, upload_to="user/%Y/%m/%d"),
        ),
    ]
