# Generated by Django 5.0.9 on 2024-11-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0012_admission_father_contact_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="College_Enrolled_Program",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admission",
            name="College_School_Address",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admission",
            name="College_School_Enrolled_Program",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admission",
            name="College_School_name",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admission",
            name="College_Type_of_School",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admission",
            name="College_Year_Graduated",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admission",
            name="Complete_Transcript_of_Record_with_date_of_graduation",
            field=models.ImageField(
                blank=True,
                upload_to="Complete Transcript of Records with date of graduation/%Y/%m/%d",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="Elementary_School_Address",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admission",
            name="Elementary_School_name",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admission",
            name="Elementary_Type_of_school",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admission",
            name="Elementary_Year_of_graduated",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admission",
            name="Senior_High_School_Address",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admission",
            name="Senior_High_School_Graduated",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admission",
            name="Senior_High_School_Name",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admission",
            name="Senior_High_School_Type_of_School",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
