# Generated by Django 5.0.9 on 2024-11-26 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0014_admission_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Regular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Student_Regular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Student_Regular",
                        to="Enrollments.admission",
                    ),
                ),
            ],
        ),
    ]
