# Generated by Django 5.0.9 on 2024-11-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0015_regular"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admission",
            old_name="Prefered_program",
            new_name="Preferred_program",
        ),
    ]
