# Generated by Django 5.0.9 on 2024-11-28 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0016_rename_prefered_program_admission_preferred_program"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admission",
            name="Student",
        ),
    ]
