# Generated by Django 5.0.9 on 2024-11-28 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0017_remove_admission_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admission",
            name="College_School_Enrolled_Program",
        ),
    ]
