# Generated by Django 5.0.9 on 2024-11-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0018_remove_admission_college_school_enrolled_program"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admission",
            name="Family_name",
        ),
    ]
