# Generated by Django 5.0.9 on 2024-11-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0019_remove_admission_family_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admission",
            name="Complete_Transcript_of_Record_with_date_of_graduation",
        ),
        migrations.AddField(
            model_name="admission",
            name="Additional_Documents",
            field=models.ImageField(
                blank=True, upload_to="Admission/passport/%Y/%m/%d"
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="Form_137",
            field=models.ImageField(blank=True, upload_to="Admission/Form137/%Y/%m/%d"),
        ),
        migrations.AddField(
            model_name="admission",
            name="Passport",
            field=models.ImageField(
                blank=True, upload_to="Admission/passport/%Y/%m/%d"
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="Report_Card",
            field=models.ImageField(
                blank=True, upload_to="Admission/Report_Card/%Y/%m/%d"
            ),
        ),
    ]
