# Generated by Django 5.0.9 on 2024-12-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bscs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstyearsection",
            name="student",
            field=models.ManyToManyField(
                related_name="Student_first_year", to="bscs.student"
            ),
        ),
    ]
