# Generated by Django 5.0.9 on 2024-12-01 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bscs", "0002_firstyearsection_student"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="instructor",
        ),
        migrations.DeleteModel(
            name="Instructor",
        ),
        migrations.AddField(
            model_name="subject",
            name="Instructor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Instructors",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
