# Generated by Django 5.0.9 on 2024-12-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bscs", "0003_remove_subject_instructor_delete_instructor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secondyearsection",
            name="created_at",
        ),
        migrations.AddField(
            model_name="secondyearsection",
            name="student",
            field=models.ManyToManyField(
                related_name="Student_Second_year", to="bscs.student"
            ),
        ),
        migrations.CreateModel(
            name="FourthYearSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FourthYearSection",
                    models.CharField(
                        choices=[
                            ("BSCS 2-1", "BSCS 2-1"),
                            ("BSCS 2-2", "BSCS 2-2"),
                            ("BSCS 2-3", "BSCS 2-3"),
                            ("BSCS 2-4", "BSCS 2-4"),
                            ("BSCS 2-5", "BSCS 2-5"),
                        ],
                        default="BSCS 2-1",
                        max_length=8,
                    ),
                ),
                (
                    "student",
                    models.ManyToManyField(
                        related_name="Student_Fourth_year", to="bscs.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThirdYearSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ThirdYearSection",
                    models.CharField(
                        choices=[
                            ("BSCS 2-1", "BSCS 2-1"),
                            ("BSCS 2-2", "BSCS 2-2"),
                            ("BSCS 2-3", "BSCS 2-3"),
                            ("BSCS 2-4", "BSCS 2-4"),
                            ("BSCS 2-5", "BSCS 2-5"),
                        ],
                        default="BSCS 2-1",
                        max_length=8,
                    ),
                ),
                (
                    "student",
                    models.ManyToManyField(
                        related_name="Third_first_year", to="bscs.student"
                    ),
                ),
            ],
        ),
    ]
