# Generated by Django 5.0.9 on 2024-12-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bscs", "0005_remove_firstyearsection_student_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="year_section",
        ),
        migrations.AddField(
            model_name="subject",
            name="year_section",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Subjects",
                to="bscs.firstyearsection",
            ),
            preserve_default=False,
        ),
    ]
