# Generated by Django 5.0.9 on 2024-12-01 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bscs", "0007_firstyearsection_grades_student_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstyearsection",
            name="grades",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="bscs.subject",
            ),
        ),
        migrations.RemoveField(
            model_name="student",
            name="subject",
        ),
        migrations.AddField(
            model_name="student",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_student",
                to="bscs.subject",
            ),
            preserve_default=False,
        ),
    ]
