# Generated by Django 5.0.9 on 2024-12-02 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bscs", "0008_alter_firstyearsection_grades_remove_student_subject_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_name", models.CharField(max_length=250)),
                ("Middle_name", models.CharField(max_length=250)),
                ("Last_name", models.CharField(max_length=250)),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, upload_to="instructors/"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="firstyearsection",
            name="grades",
        ),
        migrations.RemoveField(
            model_name="student",
            name="subject",
        ),
        migrations.CreateModel(
            name="Fourth_Year_Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_code", models.CharField(max_length=250)),
                (
                    "Fourth_Year_Subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Fourth_year_subjects",
                        to="bscs.firstyearsection",
                    ),
                ),
                (
                    "Instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Fourth_year_Instructors",
                        to="bscs.instructor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="First_Year_Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_code", models.CharField(max_length=250)),
                (
                    "First_Year_Subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="First_year_Subjects",
                        to="bscs.firstyearsection",
                    ),
                ),
                (
                    "Instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="First_year_Instructors",
                        to="bscs.instructor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Second_Year_Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_code", models.CharField(max_length=250)),
                (
                    "Instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Second_year_Instructors",
                        to="bscs.instructor",
                    ),
                ),
                (
                    "Second_Year_Subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Second_year_Subjects",
                        to="bscs.firstyearsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Third_Year_Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_code", models.CharField(max_length=250)),
                (
                    "Instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Third_year_Instructors",
                        to="bscs.instructor",
                    ),
                ),
                (
                    "Third_Year_Subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Third_Year_Subject",
                        to="bscs.firstyearsection",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
