# Generated by Django 5.0.9 on 2024-12-02 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bscs", "0009_instructor_remove_firstyearsection_grades_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstyearsection",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Student_first_year",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
