# Generated by Django 5.0.9 on 2024-12-02 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bscs", "0014_remove_first_year_subject_first_year_subject_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Instructor",
        ),
    ]
