# Generated by Django 5.0.9 on 2024-11-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="photo",
            new_name="profile_photo",
        ),
    ]
