# Generated by Django 5.0.9 on 2024-11-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_rename_photo_profile_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[
                    ("SH", "Senior HighSchool Graduate"),
                    ("AL", "Alternative Learning System"),
                    ("FU", "Foreign undergraduate student applicant"),
                    ("CE", "Currently enrolled Grade12 student"),
                    ("BD", "Bachelor degree graduate"),
                    ("TC", "Teacher certificate program applicant"),
                    ("TF", "Transferee"),
                    ("DC", "Diploma certificate associate vocational graduate"),
                ],
                default="SH",
                max_length=2,
            ),
        ),
    ]
