# Generated by Django 5.0.9 on 2024-11-20 04:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_profile_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="Admission",
        ),
        migrations.RenameField(
            model_name="admission",
            old_name="status",
            new_name="type_of_applicant",
        ),
    ]
