# Generated by Django 5.0.9 on 2024-11-20 05:07

import django.utils.timezone
import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_rename_profile_admission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="country",
            field=django_countries.fields.CountryField(
                default=django.utils.timezone.now, max_length=2
            ),
            preserve_default=False,
        ),
    ]
