# Generated by Django 5.0.9 on 2024-11-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_admission_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admission",
            old_name="type_of_applicant",
            new_name="Type_of_applicant",
        ),
        migrations.AddField(
            model_name="admission",
            name="Senior_high_school_strand",
            field=models.CharField(
                choices=[
                    ("AB", "Accountancy Business Management"),
                    ("ST", "Science, Technology, Engineering and Mathematics"),
                    ("HS", "Humanities and Social Science"),
                    ("GA", "General Academic"),
                ],
                default="AB",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="senior_high_school_track",
            field=models.CharField(
                choices=[
                    ("AC", "Academic"),
                    ("AD", "Arts and Design"),
                    ("SP", "Sports"),
                    ("TL", "Technical Vocational Livelihood"),
                ],
                default="AC",
                max_length=2,
            ),
        ),
    ]
