# Generated by Django 5.0.9 on 2024-12-12 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0009_delete_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "Student_profile_photo",
                    models.ImageField(blank=True, upload_to="user/%Y/%m/%d"),
                ),
                ("Full_name", models.CharField(max_length=250)),
                ("First_name", models.CharField(max_length=250)),
                ("Middle_name", models.CharField(blank=True, max_length=250)),
                ("Last_name", models.CharField(blank=True, max_length=250)),
                ("StudentID", models.CharField(max_length=250, unique=True)),
                (
                    "UserStudentProfile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
