# Generated by Django 5.0.9 on 2024-12-12 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="UserStudentProfile",
            new_name="User_Student_Profile",
        ),
    ]
