# Generated by Django 5.0.9 on 2024-12-12 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bscs_year_courses", "0001_initial"),
        (
            "bscs_year_section",
            "0005_alter_fourthyearsection_fourthyearsection_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstYearFirstSemesterStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Full_name", models.CharField(max_length=250)),
                ("First_name", models.CharField(max_length=250)),
                ("Middle_name", models.CharField(blank=True, max_length=250)),
                ("Last_name", models.CharField(blank=True, max_length=250)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, upload_to="StudentProfile/"),
                ),
                ("StudentID", models.CharField(max_length=250, unique=True)),
                (
                    "Type_of_student",
                    models.CharField(
                        choices=[("REGULAR", "REGULAR"), ("IRREGULAR", "IRREGULAR")],
                        max_length=9,
                    ),
                ),
                (
                    "First_Year_Second_Semester_Course",
                    models.ManyToManyField(
                        blank=True,
                        related_name="FirstYearFirstSemesterStudentsCourses",
                        to="bscs_year_courses.firstyearsecondsemestercourse",
                    ),
                ),
                (
                    "UserStudentProfile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "first_year_first_semester_courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="FirstYearFirstSemesterStudentsCourses",
                        to="bscs_year_courses.firstyearfirstsemestercourses",
                    ),
                ),
                (
                    "year_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="year_section_student",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
    ]
