# Generated by Django 5.0.9 on 2024-12-02 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bscs_year_section", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="First_year_Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Full_name", models.CharField(max_length=250)),
                ("First_name", models.CharField(max_length=250)),
                ("Middle_name", models.CharField(blank=True, max_length=250)),
                ("Last_name", models.CharField(blank=True, max_length=250)),
                (
                    "Student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "year_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="year_section_student",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
    ]
