# Generated by Django 5.0.9 on 2024-12-12 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_initial"),
        ("bscs_student", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firstyearfirstsemesterstudent",
            name="First_name",
        ),
        migrations.RemoveField(
            model_name="firstyearfirstsemesterstudent",
            name="Full_name",
        ),
        migrations.RemoveField(
            model_name="firstyearfirstsemesterstudent",
            name="Last_name",
        ),
        migrations.RemoveField(
            model_name="firstyearfirstsemesterstudent",
            name="Middle_name",
        ),
        migrations.RemoveField(
            model_name="firstyearfirstsemesterstudent",
            name="StudentID",
        ),
        migrations.RemoveField(
            model_name="firstyearfirstsemesterstudent",
            name="UserStudentProfile",
        ),
        migrations.RemoveField(
            model_name="firstyearfirstsemesterstudent",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="firstyearfirstsemesterstudent",
            name="Student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Profile_Student",
                to="account.profile",
            ),
            preserve_default=False,
        ),
    ]
