# Generated by Django 5.0.9 on 2024-12-03 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bscs_student", "0002_rename_first_year_student_firstyearstudent"),
        ("bscs_year_subjects", "0004_firstyearsubject_room_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstyearstudent",
            name="first_year_subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bscs_year_subjects.firstyearsubject",
            ),
            preserve_default=False,
        ),
    ]
