# Generated by Django 5.0.9 on 2024-12-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bscs_student",
            "0002_remove_firstyearfirstsemesterstudent_first_name_and_more",
        ),
        ("bscs_year_courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstyearfirstsemesterstudent",
            name="Second_Year_First_Semester_Courses",
            field=models.ManyToManyField(
                blank=True,
                related_name="SecondYearFirstSemesterStudentCourses",
                to="bscs_year_courses.secondyearfirstsemestercourses",
            ),
        ),
        migrations.AddField(
            model_name="firstyearfirstsemesterstudent",
            name="Second_Year_Second_Semester_Courses",
            field=models.ManyToManyField(
                blank=True,
                related_name="SecondYearSecondSemesterStudentCourses",
                to="bscs_year_courses.secondyearsecondsemestercourses",
            ),
        ),
    ]
