# Generated by Django 5.0.9 on 2024-12-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bscs_student", "0003_firstyearstudent_first_year_subject"),
        ("bscs_year_subjects", "0004_firstyearsubject_room_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firstyearstudent",
            name="first_year_subject",
        ),
        migrations.AddField(
            model_name="firstyearstudent",
            name="first_year_subject",
            field=models.ManyToManyField(
                related_name="FirstYearStudents",
                to="bscs_year_subjects.firstyearsubject",
            ),
        ),
    ]
