# Generated by Django 5.0.9 on 2024-12-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_rename_userstudentprofile_profile_user_student_profile"),
        (
            "bscs_student",
            "0003_firstyearfirstsemesterstudent_second_year_first_semester_courses_and_more",
        ),
        ("bscs_year_courses", "0001_initial"),
        (
            "bscs_year_section",
            "0005_alter_fourthyearsection_fourthyearsection_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FirstYearFirstSemesterStudent",
            new_name="BSCSFirstYearStudent",
        ),
    ]
