# Generated by Django 5.0.9 on 2024-12-14 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bscs_student", "0005_rename_bscsfirstyearstudent_bscsstudent"),
        ("bscs_year_courses", "0001_initial"),
        (
            "bscs_year_section",
            "0005_alter_fourthyearsection_fourthyearsection_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bscsstudent",
            name="year_section",
        ),
        migrations.AddField(
            model_name="bscsstudent",
            name="First_year_section",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fist_year_section_student",
                to="bscs_year_section.firstyearsection",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bscsstudent",
            name="FourthYearFirstSemesterCourses",
            field=models.ManyToManyField(
                blank=True,
                related_name="FourthYearFirstSemesterStudentCourses",
                to="bscs_year_courses.fourthyearfirstsemestercourses",
            ),
        ),
        migrations.AddField(
            model_name="bscsstudent",
            name="FourthYearSecondSemesterCourses",
            field=models.ManyToManyField(
                blank=True,
                related_name="FourthYearSecondSemesterStudentCourses",
                to="bscs_year_courses.fourthyearsecondsemestercourses",
            ),
        ),
        migrations.AddField(
            model_name="bscsstudent",
            name="FourthYearSection",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Fourth_year_section_student",
                to="bscs_year_section.fourthyearsection",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bscsstudent",
            name="SecondYearSection",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="second_year_section_student",
                to="bscs_year_section.secondyearsection",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bscsstudent",
            name="ThirdYearFirstSemesterCourses",
            field=models.ManyToManyField(
                blank=True,
                related_name="ThirdYearFirstSemesterStudentCourses",
                to="bscs_year_courses.thirdyearfirstsemestercourses",
            ),
        ),
        migrations.AddField(
            model_name="bscsstudent",
            name="ThirdYearSecondSemesterCourses",
            field=models.ManyToManyField(
                blank=True,
                related_name="ThirdYearSecondThirdSemesterCourses",
                to="bscs_year_courses.thirdyearsecondsemestercourses",
            ),
        ),
        migrations.AddField(
            model_name="bscsstudent",
            name="ThirdYearSection",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Third_year_section_student",
                to="bscs_year_section.thirdyearsection",
            ),
            preserve_default=False,
        ),
    ]
