# Generated by Django 5.0.9 on 2024-12-14 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bscs_student", "0006_remove_bscsstudent_year_section_and_more"),
        (
            "bscs_year_section",
            "0005_alter_fourthyearsection_fourthyearsection_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bscsstudent",
            name="First_year_section",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fist_year_section_student",
                to="bscs_year_section.firstyearsection",
            ),
        ),
        migrations.AlterField(
            model_name="bscsstudent",
            name="FourthYearSection",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Fourth_year_section_student",
                to="bscs_year_section.fourthyearsection",
            ),
        ),
        migrations.AlterField(
            model_name="bscsstudent",
            name="SecondYearSection",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="second_year_section_student",
                to="bscs_year_section.secondyearsection",
            ),
        ),
        migrations.AlterField(
            model_name="bscsstudent",
            name="ThirdYearSection",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Third_year_section_student",
                to="bscs_year_section.thirdyearsection",
            ),
        ),
    ]
