# Generated by Django 5.0.9 on 2024-12-09 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bscs_student", "0006_firstyearstudent_type_of_student"),
        (
            "bscs_year_section",
            "0005_alter_fourthyearsection_fourthyearsection_and_more",
        ),
        (
            "bscs_year_subjects",
            "0008_rename_fourthyearsubject_fourthyearfirstsemestersubject_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FirstYearStudent",
            new_name="FirstYearFirstSemesterStudent",
        ),
        migrations.AlterField(
            model_name="firstyearfirstsemesterstudent",
            name="first_year_subject",
            field=models.ManyToManyField(
                related_name="FirstYearStudents",
                to="bscs_year_subjects.firstyearfirstsemestersubject",
            ),
        ),
    ]
