# Generated by Django 5.0.9 on 2024-12-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bscs_student",
            "0007_rename_firstyearstudent_firstyearfirstsemesterstudent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="firstyearfirstsemesterstudent",
            name="Semester",
            field=models.CharField(default="First_Semester", max_length=250),
        ),
    ]
