# Generated by Django 5.0.9 on 2024-12-14 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bscs_student", "0008_alter_bscsstudent_first_year_section_and_more"),
        (
            "bscs_year_section",
            "0005_alter_fourthyearsection_fourthyearsection_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bscsstudent",
            name="ThirdYearSection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Third_year_section_student",
                to="bscs_year_section.thirdyearsection",
            ),
        ),
    ]
