# Generated by Django 5.0.9 on 2024-12-09 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bscs_student", "0008_firstyearfirstsemesterstudent_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firstyearfirstsemesterstudent",
            name="Semester",
        ),
    ]
