# Generated by Django 5.0.9 on 2024-12-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_name", models.CharField(max_length=250)),
                ("Middle_name", models.CharField(max_length=250)),
                ("Last_name", models.CharField(max_length=250)),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, upload_to="instructors/"),
                ),
            ],
        ),
    ]
