# Generated by Django 5.0.9 on 2024-12-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bscs_instructors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="Middle_name",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
