# Generated by Django 5.0.9 on 2024-12-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bscs_instructors", "0002_alter_instructor_middle_name"),
        (
            "bscs_year_subjects",
            "0006_rename_firstyearsubject_firstyearsubject_firstyearsections_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Instructor",
            new_name="First_Year_Instructor",
        ),
    ]
