# Generated by Django 5.0.9 on 2024-12-06 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bscs_instructors", "0004_rename_first_year_instructor_firstyearinstructor"),
        ("bscs_year_subjects", "0007_remove_firstyearsubject_instructors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstyearinstructor",
            name="FirstYearSubjects",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="FirstYearSubjects_Instructor",
                to="bscs_year_subjects.firstyearsubject",
            ),
            preserve_default=False,
        ),
    ]
