# Generated by Django 5.0.9 on 2024-12-09 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bscs_instructors", "0005_firstyearinstructor_firstyearsubjects"),
        (
            "bscs_year_subjects",
            "0008_rename_fourthyearsubject_fourthyearfirstsemestersubject_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstyearinstructor",
            name="FirstYearSubjects",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="FirstYearSubjects_Instructor",
                to="bscs_year_subjects.firstyearfirstsemestersubject",
            ),
        ),
    ]
