# Generated by Django 5.0.9 on 2024-12-02 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bscs_instructors", "0001_initial"),
        ("bscs_year_section", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="First_Year_Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_code", models.CharField(max_length=250)),
                (
                    "First_Year_Subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="First_year_Subjects",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
                (
                    "Instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="First_year_Instructors",
                        to="bscs_instructors.instructor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fourth_Year_Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_code", models.CharField(max_length=250)),
                (
                    "Fourth_Year_Subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Fourth_year_subjects",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
                (
                    "Instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Fourth_year_Instructors",
                        to="bscs_instructors.instructor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Second_Year_Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_code", models.CharField(max_length=250)),
                (
                    "Instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Second_year_Instructors",
                        to="bscs_instructors.instructor",
                    ),
                ),
                (
                    "Second_Year_Subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Second_year_Subjects",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Third_Year_Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_code", models.CharField(max_length=250)),
                (
                    "Instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Third_year_Instructors",
                        to="bscs_instructors.instructor",
                    ),
                ),
                (
                    "Third_Year_Subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Third_Year_Subject",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
    ]
