# Generated by Django 5.0.9 on 2024-12-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bscs_instructors", "0001_initial"),
        ("bscs_year_section", "0001_initial"),
        (
            "bscs_year_subjects",
            "0002_rename_instructor_first_year_subject_instructors_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="First_Year_Subject",
            new_name="FirstYearSubject",
        ),
        migrations.RenameModel(
            old_name="Fourth_Year_Subject",
            new_name="FourthYearSubject",
        ),
        migrations.RenameModel(
            old_name="Second_Year_Subject",
            new_name="SecondYearSubject",
        ),
        migrations.RenameModel(
            old_name="Third_Year_Subject",
            new_name="ThirdYearSubject",
        ),
        migrations.RenameField(
            model_name="firstyearsubject",
            old_name="First_Year_Subject",
            new_name="FirstYearSubject",
        ),
    ]
