# Generated by Django 5.0.9 on 2024-12-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bscs_year_subjects",
            "0003_rename_first_year_subject_firstyearsubject_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="firstyearsubject",
            name="room_number",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fourthyearsubject",
            name="Subject_grade",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fourthyearsubject",
            name="Subject_name",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fourthyearsubject",
            name="room_number",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secondyearsubject",
            name="Subject_grade",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secondyearsubject",
            name="Subject_name",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secondyearsubject",
            name="room_number",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="thirdyearsubject",
            name="Subject_grade",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="thirdyearsubject",
            name="Subject_name",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="thirdyearsubject",
            name="room_number",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
