# Generated by Django 5.0.9 on 2024-12-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bscs_year_subjects", "0004_firstyearsubject_room_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firstyearsubject",
            name="Subject_grade",
        ),
    ]
