# Generated by Django 5.0.9 on 2024-12-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bscs_year_subjects", "0005_remove_firstyearsubject_subject_grade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="firstyearsubject",
            old_name="FirstYearSubject",
            new_name="FirstYearSections",
        ),
        migrations.RenameField(
            model_name="fourthyearsubject",
            old_name="Fourth_Year_Subject",
            new_name="Fourth_Year_Sections",
        ),
        migrations.RenameField(
            model_name="secondyearsubject",
            old_name="Second_Year_Subject",
            new_name="Second_Year_Sections",
        ),
        migrations.RenameField(
            model_name="thirdyearsubject",
            old_name="Third_Year_Subject",
            new_name="Third_Year_Sections",
        ),
    ]
