# Generated by Django 5.0.9 on 2024-12-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bscs_year_subjects",
            "0006_rename_firstyearsubject_firstyearsubject_firstyearsections_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firstyearsubject",
            name="Instructors",
        ),
        migrations.RemoveField(
            model_name="fourthyearsubject",
            name="Instructors",
        ),
        migrations.RemoveField(
            model_name="secondyearsubject",
            name="Instructors",
        ),
        migrations.RemoveField(
            model_name="thirdyearsubject",
            name="Instructors",
        ),
    ]
