# Generated by Django 5.0.9 on 2024-12-09 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bscs_year_section",
            "0005_alter_fourthyearsection_fourthyearsection_and_more",
        ),
        ("bscs_year_subjects", "0007_remove_firstyearsubject_instructors_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FourthYearSubject",
            new_name="FourthYearFirstSemesterSubject",
        ),
        migrations.RenameModel(
            old_name="SecondYearSubject",
            new_name="SecondYearFirstSemesterSubject",
        ),
        migrations.RemoveField(
            model_name="firstyearsubject",
            name="FirstYearSections",
        ),
        migrations.RemoveField(
            model_name="thirdyearsubject",
            name="Third_Year_Sections",
        ),
        migrations.CreateModel(
            name="FirstYearFirstSemesterSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_name", models.CharField(max_length=250)),
                ("Subject_code", models.CharField(max_length=250)),
                ("room_number", models.CharField(max_length=10)),
                (
                    "FirstYearSections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="First_Year_First_Semester_Subject",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FirstYearSecondSemesterSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_name", models.CharField(max_length=250)),
                ("Subject_code", models.CharField(max_length=250)),
                ("room_number", models.CharField(max_length=10)),
                (
                    "FirstYearSections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="First_YearSecond_Semester_Subject",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FourthYearSecondSemesterSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_grade", models.CharField(max_length=250)),
                ("Subject_name", models.CharField(max_length=250)),
                ("Subject_code", models.CharField(max_length=250)),
                ("room_number", models.CharField(max_length=10)),
                (
                    "Fourth_Year_Sections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Fourth_Year_Second_Semester_Subject",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecondYearSecondSemesterSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_grade", models.CharField(max_length=250)),
                ("Subject_name", models.CharField(max_length=250)),
                ("Subject_code", models.CharField(max_length=250)),
                ("room_number", models.CharField(max_length=10)),
                (
                    "Second_Year_Sections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Second_Year_Second_Semester_Subject",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThirdYearFirstSemesterSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_grade", models.CharField(max_length=250)),
                ("Subject_name", models.CharField(max_length=250)),
                ("Subject_code", models.CharField(max_length=250)),
                ("room_number", models.CharField(max_length=10)),
                (
                    "Third_Year_Sections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Third_Year_First_Semester_Subject",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThirdYearSecondSemesterSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_grade", models.CharField(max_length=250)),
                ("Subject_name", models.CharField(max_length=250)),
                ("Subject_code", models.CharField(max_length=250)),
                ("room_number", models.CharField(max_length=10)),
                (
                    "Third_Year_Sections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Third_Year_Second_Semester_Subject",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
    ]
