# Generated by Django 5.0.9 on 2024-12-09 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bscs_Student_Grades", "0003_alter_firstyearstudentgrade_student_subject"),
        ("bscs_instructors", "0006_alter_firstyearinstructor_firstyearsubjects"),
        (
            "bscs_student",
            "0007_rename_firstyearstudent_firstyearfirstsemesterstudent_and_more",
        ),
        (
            "bscs_year_subjects",
            "0008_rename_fourthyearsubject_fourthyearfirstsemestersubject_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="FirstYearSubject",
        ),
        migrations.DeleteModel(
            name="ThirdYearSubject",
        ),
    ]
