# Generated by Django 5.0.9 on 2024-12-14 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bscs_year_courses", "0001_initial"),
        (
            "bscs_year_section",
            "0005_alter_fourthyearsection_fourthyearsection_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstYearFirstSemesterStudentGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Grades", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "First_Year_Sections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="First_year_Sections",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
                (
                    "Student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="First_year_student_grade",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Student_Courses",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Student_Course_Grade",
                        to="bscs_year_courses.firstyearfirstsemestercourses",
                    ),
                ),
            ],
        ),
    ]
