# Generated by Django 5.0.9 on 2024-12-14 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bscs_Student_Grades", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firstyearfirstsemesterstudentgrade",
            name="First_Year_Sections",
        ),
    ]
