# Generated by Django 5.0.9 on 2024-12-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bscs_Student_Grades", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firstyearstudentgrade",
            name="date_recorded",
        ),
    ]
