# Generated by Django 5.0.9 on 2024-12-09 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bscs_Student_Grades", "0002_remove_firstyearstudentgrade_date_recorded"),
        (
            "bscs_year_subjects",
            "0008_rename_fourthyearsubject_fourthyearfirstsemestersubject_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstyearstudentgrade",
            name="Student_Subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Student_grades",
                to="bscs_year_subjects.firstyearfirstsemestersubject",
            ),
        ),
    ]
