from django import forms
from .models import Admission
from django.conf import settings
class AdmissionForm(forms.ModelForm):
    class Meta:
        model = Admission
        fields = ['Type_of_applicant',
                  'senior_high_school_track',
                  'Senior_high_school_strand',
                  'Preferred_program',
                  'full_name',
                  'Given_name',
                  'Middle_name',
                  'last_name',
                  'Suffix',
                  'Date_of_birth',
                  'Contact_number',
                  'Address_line_1',
                  'Address_line_2',
                  'City',
                  'State_Province_Region',
                  'Postal_code',
                  'photo',
                  'number_of_siblings',
                  'income_bracket',
                  'Fathers_name',
                  'Father_Contact_number',
                  'Father_Occupation',
                  'Father_has_attended_college',
                  'Mother_name',
                  'Mother_Contact_number',
                  'Mother_Occupation',
                  'Mother_has_attended_college',
                  'Guardian_name',
                  'Guardian_Contact_number',
                  'Guardian_Occupation',
                  'Elementary_School_name',
                  'Elementary_School_Address',
                  'Elementary_Type_of_school',
                  'Elementary_Year_of_graduated',
                  'Senior_High_School_Name',
                  'Senior_High_School_Address',
                  'Senior_High_School_Type_of_School',
                  'Senior_High_School_Graduated',
                  'College_School_name',
                  'College_Enrolled_Program',
                  'College_School_Address',
                  'College_Type_of_School',
                  'College_Year_Graduated',
                  'Report_Card',
                  'Form_137',
                  'Passport',
                  'Additional_Documents',
                  ]


