# Generated by Django 5.0.9 on 2024-12-10 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "bscs_year_section",
            "0005_alter_fourthyearsection_fourthyearsection_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstYearFirstSemesterCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_name", models.CharField(max_length=250)),
                ("Subject_code", models.CharField(max_length=250)),
                ("room_number", models.CharField(max_length=10)),
                (
                    "FirstYearSections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="First_Year_First_Semester_Courses",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FirstYearSecondSemesterCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_name", models.CharField(max_length=250)),
                ("Subject_code", models.CharField(max_length=250)),
                ("room_number", models.CharField(max_length=10)),
                (
                    "FirstYearSections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="First_YearSecond_Semester_Courses",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FourthYearFirstSemesterCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_grade", models.CharField(max_length=250)),
                ("Subject_name", models.CharField(max_length=250)),
                ("Subject_code", models.CharField(max_length=250)),
                ("room_number", models.CharField(max_length=10)),
                (
                    "Fourth_Year_Sections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Fourth_year_Courses",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FourthYearSecondSemesterCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_grade", models.CharField(max_length=250)),
                ("Subject_name", models.CharField(max_length=250)),
                ("Subject_code", models.CharField(max_length=250)),
                ("room_number", models.CharField(max_length=10)),
                (
                    "Fourth_Year_Sections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Fourth_Year_Second_Semester_Courses",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecondYearFirstSemesterCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_grade", models.CharField(max_length=250)),
                ("Subject_name", models.CharField(max_length=250)),
                ("Subject_code", models.CharField(max_length=250)),
                ("room_number", models.CharField(max_length=10)),
                (
                    "Second_Year_Sections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Second_year_Courses",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecondYearSecondSemesterCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_grade", models.CharField(max_length=250)),
                ("Subject_name", models.CharField(max_length=250)),
                ("Subject_code", models.CharField(max_length=250)),
                ("room_number", models.CharField(max_length=10)),
                (
                    "Second_Year_Sections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Second_Year_Second_Semester_Courses",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThirdYearFirstSemesterCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_grade", models.CharField(max_length=250)),
                ("Subject_name", models.CharField(max_length=250)),
                ("Subject_code", models.CharField(max_length=250)),
                ("room_number", models.CharField(max_length=10)),
                (
                    "Third_Year_Sections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Third_Year_First_Semester_Courses",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThirdYearSecondSemesterCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject_grade", models.CharField(max_length=250)),
                ("Subject_name", models.CharField(max_length=250)),
                ("Subject_code", models.CharField(max_length=250)),
                ("room_number", models.CharField(max_length=10)),
                (
                    "Third_Year_Sections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Third_Year_Second_Semester_Courses",
                        to="bscs_year_section.firstyearsection",
                    ),
                ),
            ],
        ),
    ]
