# Generated by Django 5.0.9 on 2024-12-02 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstYearSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_year_section",
                    models.CharField(
                        choices=[
                            ("BSCS 1-1", "BSCS 1-1"),
                            ("BSCS 1-2", "BSCS 1-2"),
                            ("BSCS 1-3", "BSCS 1-3"),
                            ("BSCS 1-4", "BSCS 1-4"),
                            ("BSCS 1-5", "BSCS 1-5"),
                        ],
                        default="BSCS 1-1",
                        max_length=8,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Student_first_year",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["first_year_section"],
            },
        ),
        migrations.CreateModel(
            name="FourthYearSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FourthYearSection",
                    models.CharField(
                        choices=[
                            ("BSCS 2-1", "BSCS 2-1"),
                            ("BSCS 2-2", "BSCS 2-2"),
                            ("BSCS 2-3", "BSCS 2-3"),
                            ("BSCS 2-4", "BSCS 2-4"),
                            ("BSCS 2-5", "BSCS 2-5"),
                        ],
                        default="BSCS 2-1",
                        max_length=8,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Student_fourth_year",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecondYearSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "second_year_section",
                    models.CharField(
                        choices=[
                            ("BSCS 2-1", "BSCS 2-1"),
                            ("BSCS 2-2", "BSCS 2-2"),
                            ("BSCS 2-3", "BSCS 2-3"),
                            ("BSCS 2-4", "BSCS 2-4"),
                            ("BSCS 2-5", "BSCS 2-5"),
                        ],
                        default="BSCS 2-1",
                        max_length=8,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Student_second_year",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThirdYearSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ThirdYearSection",
                    models.CharField(
                        choices=[
                            ("BSCS 2-1", "BSCS 2-1"),
                            ("BSCS 2-2", "BSCS 2-2"),
                            ("BSCS 2-3", "BSCS 2-3"),
                            ("BSCS 2-4", "BSCS 2-4"),
                            ("BSCS 2-5", "BSCS 2-5"),
                        ],
                        default="BSCS 2-1",
                        max_length=8,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Student_third_year",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
