# Generated by Django 5.0.9 on 2024-12-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bscs_year_section", "0002_remove_firstyearsection_student_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firstyearsection",
            name="room_number",
        ),
    ]
